example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_catalog

app_name = 'katalog'

urlpatterns = [
    path('', show_catalog, name='show_catalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist,show_xml,show_json,show_json_by_id,show_xml_by_id

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('katalog/', include('katalog.urls')),
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import (
    add_task,
    create_task,
    delete_task,
    show_todolist,
    register,
    login_user,
    logout_user,
    update_finished,
    show_json
)

app_name = "todolist"
urlpatterns = [
    path("", show_todolist, name="show_todolist"),
    path("login/", login_user, name="login"),
    path("register/", register, name="register"),
    path("create-task/", create_task, name="create_task"),
    path("logout/", logout_user, name="logout"),
    path("delete-task/<int:id>", delete_task, name="delete_task"),
    path("update-finished/<int:id>", update_finished, name="update_finished"),
    path("json/", show_json, name="show_json"),
    path("add/", add_task, name="add_task"),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models
class MyWatchList(models.Model):
    watched = models.BooleanField()
    title = models.TextField()
    rating = models.FloatField()
    release_date = models.DateField()
    review = models.TextField()
# Create your models here.

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

# TODO: Create your views here.
def show_catalog(request):
    return render(request,"katalog.html", context)

data_katalog_item = CatalogItem.objects.all()
context ={
    'list_item' : data_katalog_item,
    'name': 'Nicolas Ananda',
    'NPM' : '2106720973'
}

mywatchlist/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from mywatchlist.models import MyWatchList

# Create your views here.
def show_mywatchlist(request):
    data_mywatchlist_item = MyWatchList.objects.all()
    udahnonton = 0
    belumnonton = 0

    for i in data_mywatchlist_item:
        if i.watched == True:
            udahnonton += 1
        elif i.watched == False:
            belumnonton += 1
            
    context ={
        'list_item' : data_mywatchlist_item,
        'name': 'Nicolas Ananda',
        'NPM' : '2106720973',
        'udahnonton' : udahnonton,
        'belumnonton' : belumnonton,
    }
    
    return render(request,"mywatchlist.html", context)

def show_xml(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")


def show_json(request):
    data = MyWatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_json_by_id(request,id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")
   

def show_xml_by_id(request,id):
    data = MyWatchList.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

todolist/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core import serializers
from todolist.models import Task
import datetime

# Create your views here.


@login_required(login_url="/todolist/login/")
def show_todolist(request):
    todolist_data = Task.objects.filter(user=request.user)
    context = {
        "todolist": todolist_data, 
        "username": request.user,
    }
    return render(request, "todolist.html", context)


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Account succesfully created!")
            return redirect("todolist:login")

    context = {"form": form}
    return render(request, "register.html", context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(
                reverse("todolist:show_todolist")
            )
            response.set_cookie(
                "last_login", str(datetime.datetime.now())
            )
            return response
        else:
            messages.info(request, 'Wrong Username or Password!')
    context = {}
    return render(request, 'login.html', context)


def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse("todolist:login"))
    response.delete_cookie("last_login")
    return response


@login_required(login_url="/todolist/login/")
def create_task(request):
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        Task.objects.create(
            user=request.user,
            title=title,
            description=description,
            date=datetime.datetime.today(),
        )
        return HttpResponseRedirect(reverse("todolist:show_todolist"))
    return render(request, "create_task.html")


def delete_task(request, id):
    task = Task.objects.get(user=request.user, id=id)
    task.delete()
    return HttpResponseRedirect(reverse("todolist:show_todolist"))


def update_finished(request, id):
    task = Task.objects.get(user=request.user, id=id)
    task.is_finished = not task.is_finished
    task.save(update_fields=["is_finished"])
    return HttpResponseRedirect(reverse("todolist:show_todolist"))

# json
@login_required(login_url="/todolist/login/")
def show_json(request):
    task = Task.objects.filter(user=request.user)
    return HttpResponse(
        serializers.serialize("json", task), content_type="application/json"
    )


def add_task(request):
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        task = Task.objects.create(
            user=request.user,
            title=title,
            description=description,
            date=datetime.datetime.today(),
        )
        return JsonResponse( 
            {
                "pk": task.id,
                "fields": {
                    "title": task.title,
                    "description": task.description,
                    "is_finished": task.is_finished,
                    "date": task.date,
                },
            },
            status=200,
        )

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <style>
    h1,h3{
      color: rgb(105, 254, 135);
    }
  </style>

  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}
 {% block content %}
 <style>
   table, th, td{
   border:1.5px solid black;
   border-collapse:collapse;
   text-align:left;
 </style>
 <body style="margin:auto">
  <h1 >Assignment 2 PBD</h1>
  <br/>
  <h5>{{name}}</h5>

  <h5>{{NPM}}</h5>
  <br/>


  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_item %}
      <tr>
        <td>{{item.item_name}}</td>
        <td>{{item.item_price}}</td>
        <td>{{item.item_stock}}</td>
        <td>{{item.rating}}</td>
        <td>{{item.description}}</td>
        <td>{{item.item_url}}</td>
      </tr>
    {% endfor %}
  </table>
 </body>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}
 {% block content %}
 <style>
   table, th, td{
   border:1.5px solid black;
   border-collapse:collapse;
   text-align:left;
   }
   body{
    margin:auto;
   }
 </style>
 <body>
  <h1 >Assignment 3 PBD</h1>
  <br/>
  <h5>{{name}}</h5>

  <h5>{{NPM}}</h5>
  <br/>


  <table>
    <tr>
      <th>Watched</th>
      <th>Title</Title></th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for item in list_item %}
    <tr>
        <tbody>
            <th>
              {% if item.watched %}<p class="watched">YES</p>
              {% else %}<p class="not">NO</p>{% endif %}
              
            </th>
            <th>{{item.title}}</th>
            <th>{{item.rating}}</th>
            <th>{{item.release_date}}</th>
            <th>{{item.review}}</th>
        </tbody>
    </tr>
    {% endfor %}
  </table>

 </body>
  {% if udahnonton > belumnonton %}
  <p>Congratulations, you have watched a lot of movies!</p>
  {% else %}
  <p>Woah, you need to watch more movies!</p>
  {% endif %}

 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/create_task.html
{% extends "base.html" %}
{% block content %}

<h3>{{ title }}</h3>
<body style="text-align:center">
    <h1 style="margin-bottom: 7px;">Create Task</h1>
<form method="post">
    {% csrf_token %}
    <div class="col text-center">
    <div class="form-floating mb-3 w-10">
        <input  type="text" class="form-control" name="title" id="floatingInput" placeholder="Task Name">
        <label for="floatingInput">Title</label></div>
        <div class="form-floating">
        <input type="text" class="form-control" name="description" id="floatingInput" placeholder="Task Name" required>
        <label for="floatingInput">Description</label>
        <button class="btn btn-success my-3" type="submit">Create Task</button>
    </div>
</div>
</form>
</body>

{% endblock %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<style>
    body{
        background-image: url("");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-color: aliceblue;    
    }
    div-all {
        margin-right: 100px;
        margin-left: 100px;
        border-style: solid;
        text-align: left;
    }
    h1 {
  text-align: center;
  color: purple;
} 
tr.user{
    text-align: center;
    color: blue
}
p{
  text-align: center;
  color: black;
}  
</style>
<body>

<div class="all">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <div class="form-floating mb-3 w-20">
            <input type="text" class="form-control" name="username" id="floatingInput" placeholder="Username" required>
            <label for="floatingInput">Username</label>
          </div>
          <div class="form-floating">
            <input type="password" class="form-control" name="password" id="floatingPassword" placeholder="Password" required>
            <label for="floatingPassword">Password</label>
          </div>
          <div class="col text-center my-3">
            <input class="btn btn-success" type="submit" value="Login">
          </div>

    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p>Don't have an account? <a href="{% url 'todolist:register' %}">Create Account</a></p>

</div>
</body>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Account Registration</title>
{% endblock meta %}

{% block content %}
<style>
    table, tr, td{
    border:1.5px solid black;
    border-collapse:collapse;
    text-align:left;
    }
    body{
        margin:3px;
}
</style>

<div class = "container-md">
    <h1 style="color:blueviolet">Registration Form</h1>

        <form method="POST" >
            {% csrf_token %}
            <table>
                {{ form.as_table }}
                <tr></tr>
            </table>
            <button class="btn btn-success mx-auto my-3" type="submit" >Daftar</button>
        </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
                {% endfor %}
        </ul>
    {% endif %}

</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}
<script>
    $(document).ready(function() {
    function card(task) {
        return `
    <div class="card text-center mx-auto my-3 mb-3" style="border-radius: 10px; width: 15rem; background-color: bisque;">
        <div class="card-body">
        <h6 class="card-subtitle mb-2" style="margin-top:5px;">${task.fields.title} - ${task.fields.date}</h6>
        <p class="card-text">${task.fields.description}</p>
        <div class="custom-control custom-checkbox">
            
            <input type="checkbox" class="custom-control-input" onclick="location.href='update-finished/${task.pk}'" ${task.fields.is_finished ? "checked" : ""}>
            <label class="custom-control-label" for="#">Task Status</label>
        </div>
        <button class="btn btn-outline-danger btn-sm" style="margin-top: 3px ; margin-bottom: -5px; ;"><a href="delete-task/${task.pk}">Delete Task</a></button>
        </div>
  </div>
  `};
  function forloop() {
        $.get("{% url 'todolist:show_json' %}", function(data) {
            $.each(data, function(i, value) {
                $("#refer").append(card(value));
            });
        });
    };
    $("#submitbutton").click(e => {
      e.preventDefault();
      const csrftoken = document.querySelector(
        "[name=csrfmiddlewaretoken]"
      ).value;
      $.ajax({
          type: "POST",
          url: "{% url 'todolist:add_task' %}",
          headers: { "X-CSRFToken": csrftoken },
          mode: "same-origin",
          data: {
            title: $("#titleinput").val(),
            description: $("#descinput").val(),
          },
          success: response => {
            $("#addtask").trigger("reset");
            $("#refer").prepend(card(response));
          },
          error: error => {
            console.log(error);
          },
        });
    });
    forloop();
})
</script>
<div class="modal fade" id="modall" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
      <div class="modal-body">
        <form method="post" id="addtask">
            {% csrf_token %}
            <div class="col text-center">
            <div class="form-floating mb-3 w-10">
                <input  type="text" class="form-control" name="title" id="titleinput" placeholder="Task Name">
                <label for="floatingInput">Title</label></div>
                <div class="form-floating">
                <input type="text" class="form-control" name="description" id="descinput" placeholder="Task Name" required>
                <label for="floatingInput">Description</label>
                <button class="btn btn-success my-3" type="submit" id="submitbutton" data-bs-dismiss="modal">Create Task</button>
            </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: gray;">
    <div class="container-fluid">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
                <a class="navbar-brand">
                    Hi, {{username}}
                </a>
            </li>
            <li class="nav-item">
                <button class="btn btn-light btn-outline-warning btn-sm" data-bs-toggle="modal" data-bs-target="#modall">Create Task</button>
                <button class="btn btn-light btn-outline-danger btn-sm" type="button"><a href="{% url 'todolist:logout' %}">Logout</a></button>
            </li>
        </ul>
    </div>
</nav>

<div id="refer" class="row row-cols-1 row-cols-md-5 g-4 my-auto">
{% for task in todolist %}


{% endfor %}
</div>

{% endblock content %}